name = "pedidos-tacos-el-compa"
main = "src/worker.js"
compatibility_date = "2024-12-01"
account_id = "5220ba70c5fb9ba5052aad13c1bac5fc"
workers_dev = true
assets = { directory = "static", binding = "ASSETS" }

[[d1_databases]]
binding = "tacos_pedidos"
database_name = "tacos-pedidos"
database_id = "35714b3f-0931-46f1-bdb6-8c9473f603df"